import type { AgentResults } from "@/lib/agentResults";

// Renders an AgentResults bundle into a "World Bible" — a single Markdown
// document a writer/designer/director can read end-to-end. We only render
// sections whose agent produced output; missing/errored agents are skipped
// silently so the doc reads naturally on partial runs.

interface BibleOpts {
  worldTitle: string;
  thumbnailUrl?: string;
}

export function buildWorldBibleMarkdown(
  results: AgentResults,
  opts: BibleOpts,
): string {
  const a = results.agents;
  const out: string[] = [];

  out.push(`# ${opts.worldTitle}`, "");
  out.push(`*Generated by Conjure on ${new Date(results.generated_at).toLocaleString()}*`, "");
  if (opts.thumbnailUrl) {
    out.push(`![${opts.worldTitle}](${absUrl(opts.thumbnailUrl)})`, "");
  }

  // ─────────────── Establishing shot
  const scene = pick(a, "scene_describer");
  if (scene) {
    out.push(`## Establishing Shot`, "");
    if (scene.summary) out.push(strip(scene.summary), "");
    if (scene.narrative) out.push(strip(scene.narrative), "");
    if (Array.isArray(scene.tags) && scene.tags.length) {
      out.push(`**Tags:** ${scene.tags.map((t: string) => `\`${t}\``).join(", ")}`, "");
    }
  }

  // ─────────────── Place
  const placeBits: string[] = [];
  const geo = pick(a, "geolocator");
  if (geo?.candidates?.length) {
    placeBits.push(`### Likely Region`);
    for (const c of geo.candidates.slice(0, 3)) {
      placeBits.push(`- **${c.region}** (${pct(c.confidence)}) — ${strip(c.reasoning ?? "")}`);
    }
    placeBits.push("");
  }
  const era = pick(a, "era_estimator");
  if (era?.period) {
    placeBits.push(`### Era`, "");
    placeBits.push(`**${era.period}** — ${strip(era.reasoning ?? era.narrative ?? "")}`, "");
  }
  const arch = pick(a, "architectural_style");
  if (arch?.style) {
    placeBits.push(`### Architectural Style`, "");
    placeBits.push(`**${arch.style}** — ${strip(arch.reasoning ?? arch.narrative ?? "")}`, "");
  }
  const scout = pick(a, "filming_scout");
  if (scout?.locations?.length) {
    placeBits.push(`### Real-World Filming Locations`);
    for (const loc of scout.locations.slice(0, 5)) {
      placeBits.push(`- **${loc.name}** — ${loc.address ?? ""}  `);
      if (loc.match_reason) placeBits.push(`  ${strip(loc.match_reason)}`);
    }
    placeBits.push("");
  }
  if (placeBits.length) {
    out.push(`## Place`, "", ...placeBits);
  }

  // ─────────────── Look (palette + mood)
  const mood = pick(a, "mood_palette");
  if (mood) {
    out.push(`## Look & Feel`, "");
    if (mood.narrative) out.push(strip(mood.narrative), "");
    if (Array.isArray(mood.palette) && mood.palette.length) {
      out.push(`**Palette:** ${mood.palette.map((h: string) => `\`${h}\``).join(" · ")}`, "");
    }
    if (Array.isArray(mood.luts) && mood.luts.length) {
      out.push(`**Suggested LUTs:** ${mood.luts.join(", ")}`, "");
    }
    if (Array.isArray(mood.film_stocks) && mood.film_stocks.length) {
      out.push(`**Film stocks:** ${mood.film_stocks.join(", ")}`, "");
    }
  }

  // ─────────────── Spatial layout
  const spatial = pick(a, "spatial_layout");
  if (spatial) {
    out.push(`## Spatial Layout`, "");
    if (spatial.narrative) out.push(strip(spatial.narrative), "");
    if (Array.isArray(spatial.rooms) && spatial.rooms.length) {
      out.push(`**Rooms:**`);
      for (const r of spatial.rooms) {
        out.push(`- ${r.name}${r.approx_sqft ? ` (~${r.approx_sqft} sqft)` : ""}`);
      }
      if (spatial.total_sqft_estimate) {
        out.push(`- *Total ≈ ${spatial.total_sqft_estimate} sqft*`);
      }
      out.push("");
    }
    if (Array.isArray(spatial.entrances) && spatial.entrances.length) {
      out.push(`**Entrances:**`);
      for (const e of spatial.entrances) out.push(`- ${strip(e)}`);
      out.push("");
    }
    if (Array.isArray(spatial.sightlines) && spatial.sightlines.length) {
      out.push(`**Key sightlines:**`);
      for (const s of spatial.sightlines) out.push(`- ${strip(s)}`);
      out.push("");
    }
  }

  // ─────────────── Inhabitants
  const chars = pick(a, "character_suggester");
  const dialogue = pick(a, "npc_dialogue");
  if (chars?.characters?.length || dialogue?.lines?.length) {
    out.push(`## Inhabitants`, "");
    if (chars?.characters?.length) {
      for (const c of chars.characters) {
        out.push(`### ${c.name}${c.role ? ` — *${c.role}*` : ""}`);
        if (c.bio) out.push("", strip(c.bio));
        out.push("");
      }
    }
    if (dialogue?.lines?.length) {
      out.push(`### Sample Dialogue`, "");
      for (const l of dialogue.lines.slice(0, 12)) {
        out.push(`> **${l.character ?? "—"}:** ${strip(l.line ?? "")}`);
        out.push("");
      }
    }
  }

  // ─────────────── Story
  const story = pick(a, "story_seed");
  if (story?.premises?.length) {
    out.push(`## Story Seeds`, "");
    for (const p of story.premises) {
      out.push(`### ${p.title}${p.genre ? ` *(${p.genre})*` : ""}`);
      if (p.logline) out.push("", strip(p.logline));
      out.push("");
    }
  }

  // ─────────────── Production
  const shots = pick(a, "shot_list");
  const sound = pick(a, "soundscape");
  const props = pick(a, "prop_shopping");
  const dressing = pick(a, "set_dressing");
  if (shots || sound || props || dressing) {
    out.push(`## Production`, "");

    if (shots?.shots?.length) {
      out.push(`### Shot List`, "");
      for (const s of shots.shots) {
        const meta = [s.lens_mm ? `${s.lens_mm}mm` : null, s.time_of_day].filter(Boolean).join(" · ");
        out.push(`- **${s.name}**${meta ? ` (${meta})` : ""}  `);
        if (s.angle) out.push(`  ${strip(s.angle)}  `);
        if (s.notes) out.push(`  *${strip(s.notes)}*`);
      }
      out.push("");
    }

    if (sound) {
      out.push(`### Soundscape`, "");
      if (Array.isArray(sound.ambient) && sound.ambient.length) {
        out.push(`**Ambient:**`);
        for (const x of sound.ambient) out.push(`- ${strip(x)}`);
        out.push("");
      }
      if (Array.isArray(sound.foley) && sound.foley.length) {
        out.push(`**Foley:**`);
        for (const x of sound.foley) out.push(`- ${strip(x)}`);
        out.push("");
      }
    }

    if (props?.items?.length) {
      out.push(`### Prop Shopping List`, "");
      out.push(`| Prop | Vendor | Est. Price | Link |`);
      out.push(`|------|--------|-----------:|------|`);
      for (const it of props.items) {
        const price = it.price_estimate_usd != null ? `$${it.price_estimate_usd}` : "—";
        const link = it.url ? `[buy](${it.url})` : "";
        out.push(`| ${escMd(it.name)} | ${escMd(it.vendor ?? "")} | ${price} | ${link} |`);
      }
      out.push("");
    }

    if (dressing?.suggestions?.length) {
      out.push(`### Set Dressing Suggestions`, "");
      for (const s of dressing.suggestions) {
        if (typeof s === "string") out.push(`- ${strip(s)}`);
        else if (s && typeof s === "object") {
          const label = s.title ?? s.name ?? "";
          const note = s.description ?? s.note ?? s.suggestion ?? "";
          out.push(`- **${label}** — ${strip(note)}`);
        }
      }
      out.push("");
    }
  }

  // ─────────────── Practical
  const realEstate = pick(a, "real_estate");
  const hazards = pick(a, "hazard_audit");
  const access = pick(a, "accessibility");
  const carbon = pick(a, "carbon_score");
  if (realEstate || hazards || access || carbon) {
    out.push(`## Practical`, "");

    if (realEstate?.estimated_monthly_rent_usd != null) {
      out.push(`### Real Estate`, "");
      out.push(`Estimated monthly rent: **$${realEstate.estimated_monthly_rent_usd.toLocaleString()}**${realEstate.market ? ` (${realEstate.market})` : ""}`, "");
      if (realEstate.reasoning) out.push(strip(realEstate.reasoning), "");
    }

    if (hazards?.hazards?.length) {
      out.push(`### Hazards`, "");
      for (const h of hazards.hazards) {
        out.push(`- **${h.type ?? "Hazard"}** *(${h.severity ?? "?"})* — ${strip(h.description ?? "")}`);
      }
      out.push("");
    }

    if (access?.issues?.length || access?.suggestions?.length) {
      out.push(`### Accessibility`, "");
      if (access.issues?.length) {
        out.push(`**Issues:**`);
        for (const x of access.issues) out.push(`- ${strip(stringOrField(x))}`);
        out.push("");
      }
      if (access.suggestions?.length) {
        out.push(`**Suggestions:**`);
        for (const x of access.suggestions) out.push(`- ${strip(stringOrField(x))}`);
        out.push("");
      }
    }

    if (carbon?.embodied_carbon_kg_co2e != null) {
      out.push(`### Carbon Score`, "");
      out.push(`Embodied carbon estimate: **${Math.round(carbon.embodied_carbon_kg_co2e).toLocaleString()} kg CO₂e**`, "");
      if (carbon.reasoning) out.push(strip(carbon.reasoning), "");
    }
  }

  out.push("---", "");
  out.push(`*Conjure · ${results.world_id} · schema v${results.schema_version}*`);

  return out.join("\n");
}

function pick(agents: AgentResults["agents"], id: string): any {
  const e = agents[id];
  if (!e || e.status !== "done") return null;
  return e.output ?? null;
}

function strip(s: string): string {
  return String(s).replace(/\s+/g, " ").trim();
}

function pct(n: number | undefined): string {
  if (typeof n !== "number") return "?";
  return `${Math.round(n * 100)}%`;
}

function escMd(s: string): string {
  return String(s).replace(/\|/g, "\\|");
}

function stringOrField(x: any): string {
  if (typeof x === "string") return x;
  if (x && typeof x === "object") return x.description ?? x.note ?? x.title ?? JSON.stringify(x);
  return String(x);
}

function absUrl(u: string): string {
  if (/^https?:\/\//.test(u)) return u;
  if (typeof window !== "undefined") return `${window.location.origin}${u}`;
  return u;
}
