"""Generate frontend/lib/agentAddresses.ts from POST_GEN_WORKERS.

The frontend's DAG nodes need to deep-link to each agent's public profile
on Agentverse, e.g. https://agentverse.ai/agents/details/<address>/profile.
Addresses are deterministic functions of seeds, so we derive them once
here and write a static TS file the frontend imports — no runtime call to
the bridge required.

Run from backend/ whenever a seed changes in registry.POST_GEN_WORKERS:
    .venv/bin/python -m agentverse.export_addresses
"""
from __future__ import annotations

from pathlib import Path

from uagents.crypto import Identity

from agentverse.registry import POST_GEN_WORKERS

OUT_PATH = (
    Path(__file__).resolve().parents[2] / "frontend" / "lib" / "agentAddresses.ts"
)

HEADER = """\
// Auto-generated by backend/agentverse/export_addresses.py — DO NOT EDIT BY HAND.
// Source of truth: backend/agentverse/registry.py POST_GEN_WORKERS.
// Regenerate via:  python -m agentverse.export_addresses
//
// Maps each post-gen agent id to its on-network Agentverse address.
// The address is derived deterministically from the seed; if seeds change
// in the registry these addresses must be regenerated.

export const AGENT_ADDRESSES: Record<string, string> = {
"""

FOOTER = """\
};

export function agentverseProfileUrl(agentId: string): string | null {
  const addr = AGENT_ADDRESSES[agentId];
  if (!addr) return null;
  return `https://agentverse.ai/agents/details/${addr}/profile`;
}
"""


def main() -> None:
    lines: list[str] = [HEADER]
    for spec in POST_GEN_WORKERS:
        addr = Identity.from_seed(spec.seed, 0).address
        lines.append(f"  {spec.id!r}: {addr!r},\n")
    lines.append(FOOTER)
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text("".join(lines))
    print(f"wrote {OUT_PATH} ({len(POST_GEN_WORKERS)} agents)")


if __name__ == "__main__":
    main()
