// Auto-generated by backend/agentverse/export_addresses.py — DO NOT EDIT BY HAND.
// Source of truth: backend/agentverse/registry.py POST_GEN_WORKERS.
// Regenerate via:  python -m agentverse.export_addresses
//
// Maps each post-gen agent id to its on-network Agentverse address.
// The address is derived deterministically from the seed; if seeds change
// in the registry these addresses must be regenerated.

export const AGENT_ADDRESSES: Record<string, string> = {
  'scene_describer': 'agent1qfcpacmzrpll5ggejjft60fs4ekruny8qzagndag9mxm5hddax6dxk84hve',
  'object_inventory': 'agent1qv4xur7g6s6zrq8sltssejezfg83y0llm7gh5663afd7a4vjlnw8zck6h9l',
  'spatial_layout': 'agent1qfay3m9mmpeqmalfyyt50qvxez33z7052zjpjk59wwjpdsz3c0pl7465pvn',
  'geolocator': 'agent1qvnpwfwwd0uk24x65lzyvumkyz2wqkxwe8kfry6le2jyff8yqq2mw7ag3sc',
  'filming_scout': 'agent1q05km7mr8997ykktyr732vtvmy7sj6svpkzxklqe55chwl85n90g2j7jyh0',
  'era_estimator': 'agent1qtwu5kc4vnhzzfzxa8g4lcc07ezgekq9p8v89rgc0altulztp98e78zq3pd',
  'architectural_style': 'agent1q2j7sg5rfveks7t6nlsnz5zvw3clud4ydjy5ggxhguu59z2dvq9ejlj8ufa',
  'shot_list': 'agent1qvkyjsxkaxkqscv8lfat4h0r0a3w59g283v2kf2fql365lpc3kr8sxlfz0l',
  'mood_palette': 'agent1q2qkn8ru6wp06qaxzx0qmk89gthsf8s7vn3ltqnlz639932dm77qufkry05',
  'soundscape': 'agent1qtuuzzuy7n3acfj8pdemf6cvdz98aym93udznmhatru8ttxk4fmkujf23nf',
  'prop_shopping': 'agent1qt25pxh7u9ypxpnhn2vuacsshra9s40csvjwdu03tzxre90tyqe7wf7xz0r',
  'set_dressing': 'agent1q0h798yt4y96fzzexwyu98dj4fnd4v439fx3m3decswds9gm9kp2g84my0n',
  'story_seed': 'agent1qfu47u58f7ndv09l6j7k67wakl8qxz545jx4ynpx0sgy9jq2k82sytpcvt7',
  'character_suggester': 'agent1q2rgusughga7fzdkc29duuwhkezje6kxnvkaj9hw0lr2ryuv0zpk5eqpwk8',
  'npc_dialogue': 'agent1q2fqnvl0y83h04nmxx7xqs8dsant07cw4p9vlmhm4tdgmnt20gh8yjunl67',
  'real_estate': 'agent1qt9rhvagvxkmv4aj93tyr24n4xjxfzmrcumg9ua8nzsvvecglmj974s04cq',
  'hazard_audit': 'agent1qt52k06ppc084fslk2plw7mpcp06353fzst2ydw2y6eyu33fn4khgq207rk',
  'accessibility': 'agent1qddafyyxp9gutnfmts0nf4jwc8d7u7kcstnhgjqhm5qftcnlrp892806p76',
  'carbon_score': 'agent1qvkf4kkq4d2qcjl9j59sdqc2yh9vj6dhkn7sw3svp6n3eqlhq9tns0pgp7x',
};

export function agentverseProfileUrl(agentId: string): string | null {
  const addr = AGENT_ADDRESSES[agentId];
  if (!addr) return null;
  return `https://agentverse.ai/agents/details/${addr}/profile`;
}

// Build an ASI:One deep link that opens a chat targeting a specific agent
// with the analysis output prefilled as the first user message. ASI:One
// reads `?search=<text>` and auto-sends on page load, with `@<address>`
// in the text routing the message to that agent. If `output` is missing
// (agent hasn't reported yet), we still route to the agent with a generic
// kickoff message so the user always lands in a live chat.
export function asiOneAgentChatUrl(
  agentId: string,
  agentLabel: string,
  output?: unknown,
): string | null {
  const addr = AGENT_ADDRESSES[agentId];
  if (!addr) return null;
  let message: string;
  if (output !== undefined && output !== null) {
    const outputBlock =
      typeof output === "string" ? output : JSON.stringify(output, null, 2);
    message =
      `@${addr} Hey! Here is the analysis you produced for my generated world ` +
      `(you are ${agentLabel}):\n\n${outputBlock}\n\n` +
      `Can you walk me through what stood out to you and what you'd dig into next?`;
  } else {
    message =
      `@${addr} Hey ${agentLabel}! I'm exploring a generated 3D world and want ` +
      `your take on it. Can you introduce yourself, explain what you analyze, ` +
      `and walk me through what you'd want to know about a scene to do your job?`;
  }
  const params = new URLSearchParams({
    isAgentic: "true",
    search: message,
  });
  return `https://asi1.ai/chat?${params.toString()}`;
}
